# Generated by Django 2.1.7 on 2019-02-23 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=128, verbose_name='市名'),
        ),
        migrations.AlterField(
            model_name='city',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='map.Province', verbose_name='省'),
        ),
        migrations.AlterField(
            model_name='city',
            name='sce_nums',
            field=models.IntegerField(default=0, verbose_name='景点数目'),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=128, verbose_name='省名'),
        ),
        migrations.AlterField(
            model_name='province',
            name='sce_nums',
            field=models.IntegerField(default=0, verbose_name='景点数目'),
        ),
        migrations.AlterField(
            model_name='region',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='map.City', verbose_name='市'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=128, verbose_name='区名'),
        ),
        migrations.AlterField(
            model_name='region',
            name='sce_nums',
            field=models.IntegerField(default=0, verbose_name='景点数目'),
        ),
    ]
