# Generated by Django 2.1.7 on 2019-02-23 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='time',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='time',
        ),
        migrations.AddField(
            model_name='post',
            name='release_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='发表时间'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='发表时间'),
        ),
        migrations.AlterField(
            model_name='post',
            name='abstract',
            field=models.CharField(max_length=128, verbose_name='帖子摘要'),
        ),
        migrations.AlterField(
            model_name='post',
            name='clap',
            field=models.IntegerField(blank=True, null=True, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='post',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.User', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='clap',
            field=models.IntegerField(blank=True, null=True, verbose_name='对该回复点赞数'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='post.Post', verbose_name='帖子'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.User', verbose_name='用户'),
        ),
    ]
