# Generated by Django 2.1.7 on 2019-02-21 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map', '0001_initial'),
        ('scenic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('circle_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('level', models.IntegerField()),
                ('avatar', models.CharField(blank=True, max_length=512, null=True)),
                ('abstract', models.CharField(blank=True, max_length=512, null=True)),
                ('user_nums', models.IntegerField()),
                ('is_delete', models.IntegerField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='map.City')),
            ],
            options={
                'db_table': 'circle',
            },
        ),
        migrations.CreateModel(
            name='CircleRec',
            fields=[
                ('circle_rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('rec_nums', models.IntegerField()),
                ('month', models.DateField()),
                ('circle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='circle.Circle')),
                ('scenic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scenic.Scenic')),
            ],
            options={
                'db_table': 'circle_rec',
            },
        ),
    ]
