# Generated by Django 2.1.7 on 2019-02-23 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circlerec',
            name='month',
        ),
        migrations.AlterField(
            model_name='circle',
            name='abstract',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='avatar',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='map.City', verbose_name='市（外键）'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='level',
            field=models.IntegerField(default=0, verbose_name='圈子等级'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='name',
            field=models.CharField(max_length=128, verbose_name='圈名'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='user_nums',
            field=models.IntegerField(default=0, verbose_name='目前用户数'),
        ),
        migrations.AlterField(
            model_name='circlerec',
            name='rec_nums',
            field=models.IntegerField(default=0, verbose_name='打卡数'),
        ),
    ]
