# Generated by Django 2.1.7 on 2019-02-21 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceImg',
            fields=[
                ('sce_img_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_url', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'sce_img',
            },
        ),
        migrations.CreateModel(
            name='Scenic',
            fields=[
                ('scenic_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('abstract', models.CharField(max_length=4096)),
                ('detail', models.TextField(blank=True, null=True)),
                ('addr', models.CharField(max_length=512)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('cover', models.CharField(blank=True, max_length=512, null=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='map.Region')),
            ],
            options={
                'db_table': 'scenic',
            },
        ),
        migrations.AddField(
            model_name='sceimg',
            name='scenic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='scenic.Scenic'),
        ),
    ]
