# Generated by Django 2.1.7 on 2019-02-23 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sce_spider_comment',
            fields=[
                ('sce_spider_comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_nums', models.IntegerField(default=0, verbose_name='点评总数')),
                ('good_nums', models.IntegerField(default=0, verbose_name='好评数')),
            ],
            options={
                'db_table': 'sce_spider_comment',
            },
        ),
        migrations.AddField(
            model_name='scenic',
            name='hot_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='热度'),
        ),
        migrations.AddField(
            model_name='scenic',
            name='open_time',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='开放时间'),
        ),
        migrations.AddField(
            model_name='scenic',
            name='recommend_time',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='推荐游玩时间'),
        ),
        migrations.AddField(
            model_name='scenic',
            name='tel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='电话号码'),
        ),
        migrations.AddField(
            model_name='scenic',
            name='ticket',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='门票'),
        ),
        migrations.AddField(
            model_name='scenic',
            name='trans',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='交通'),
        ),
        migrations.AlterField(
            model_name='sceimg',
            name='img_url',
            field=models.CharField(max_length=512, verbose_name='景点图片'),
        ),
        migrations.AlterField(
            model_name='sceimg',
            name='scenic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='scenic.Scenic', verbose_name='景点'),
        ),
        migrations.AlterField(
            model_name='scenic',
            name='abstract',
            field=models.CharField(max_length=4096, verbose_name='景点简述'),
        ),
        migrations.AlterField(
            model_name='scenic',
            name='addr',
            field=models.CharField(max_length=512, verbose_name='景点地址'),
        ),
        migrations.AlterField(
            model_name='scenic',
            name='cover',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='scenic',
            name='detail',
            field=models.TextField(blank=True, null=True, verbose_name='景点详细描述'),
        ),
        migrations.AlterField(
            model_name='scenic',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='scenic',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='scenic',
            name='name',
            field=models.CharField(max_length=512, verbose_name='景点名'),
        ),
        migrations.AlterField(
            model_name='scenic',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='map.Region', verbose_name='区'),
        ),
        migrations.AddField(
            model_name='sce_spider_comment',
            name='scenic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='scenic.Scenic', verbose_name='景点'),
        ),
    ]
