# Generated by Django 2.1.7 on 2019-02-21 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circle', '0001_initial'),
        ('map', '0001_initial'),
        ('scenic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('friends_id', models.AutoField(primary_key=True, serialize=False)),
                ('add_time', models.DateTimeField()),
                ('is_show', models.IntegerField(blank=True, null=True)),
                ('is_delete', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'friends',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=512)),
                ('nickname', models.CharField(max_length=16)),
                ('real_name', models.CharField(blank=True, max_length=16, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('card_id', models.CharField(blank=True, max_length=18, null=True)),
                ('tel', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.CharField(blank=True, max_length=32, null=True)),
                ('avatar', models.CharField(blank=True, max_length=512, null=True)),
                ('signature', models.CharField(blank=True, max_length=256, null=True)),
                ('is_delete', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserCircle',
            fields=[
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='circle.Circle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.User')),
            ],
            options={
                'db_table': 'user_circle',
            },
        ),
        migrations.CreateModel(
            name='UserRec',
            fields=[
                ('user_rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('scenic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scenic.Scenic')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.User')),
            ],
            options={
                'db_table': 'user_rec',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='circles',
            field=models.ManyToManyField(through='user.UserCircle', to='circle.Circle'),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='map.Region'),
        ),
        migrations.AddField(
            model_name='friends',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.User'),
        ),
        migrations.AlterUniqueTogether(
            name='usercircle',
            unique_together={('circle', 'user')},
        ),
    ]
