# Generated by Django 2.1.7 on 2019-02-23 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrec',
            name='time',
        ),
        migrations.AddField(
            model_name='userrec',
            name='rec_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='打卡时间'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='is_delete',
            field=models.IntegerField(blank=True, null=True, verbose_name='黑名单等操作相关'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='is_show',
            field=models.IntegerField(blank=True, null=True, verbose_name='是否对其展示足迹'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.User', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='活了多久'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='card_id',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='circles',
            field=models.ManyToManyField(through='user.UserCircle', to='circle.Circle', verbose_name='所加的圈子'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(blank=True, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_delete',
            field=models.IntegerField(blank=True, null=True, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=16, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=512, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='real_name',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='map.Region', verbose_name='区'),
        ),
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='个性签名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='电话号码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=16, verbose_name='用户账号'),
        ),
        migrations.AlterField(
            model_name='usercircle',
            name='circle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='circle.Circle', verbose_name='圈子'),
        ),
        migrations.AlterField(
            model_name='usercircle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.User', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='userrec',
            name='scenic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scenic.Scenic', verbose_name='景点'),
        ),
        migrations.AlterField(
            model_name='userrec',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.User', verbose_name='用户'),
        ),
    ]
