# Generated by Django 2.1.7 on 2019-02-21 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenic', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComImg',
            fields=[
                ('com_img_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_url', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'com_img',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('mark', models.IntegerField()),
                ('content', models.CharField(max_length=1024)),
                ('clap', models.IntegerField(blank=True, null=True)),
                ('scenic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scenic.Scenic')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.User')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.AddField(
            model_name='comimg',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='comment.Comment'),
        ),
    ]
